# pid.conf - 热加载PID参数配置
# speed_p_l/speed_i_l/speed_d_l: 左电机速度环PID参数
# speed_p_r/speed_i_r/speed_d_r: 右电机速度环PID参数
# diff_kp/diff_kd: 差速控制PD参数
# 修改后程序会在下一帧热加载生效

speed_p_l=6.5
speed_i_l=0.0
speed_d_l=0.0
speed_p_r=6.5
speed_i_r=0.0
speed_d_r=0.0
diff_kp=10.242
diff_kd=20.274
